import type { Metadata } from "next";
// Import the styles:
import '@visa/nova-styles/styles.css';
// Import your desired theme:
import '@visa/nova-styles/themes/visa-light/index.css';
import "./globals.css";
// Compontents
import DefaultFooter from "@/components/DefaultFooter";
// main font
import { Noto_Sans } from 'next/font/google'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
 
const noto_Sans = Noto_Sans({
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={noto_Sans.className}>
      <body>
        {children}
        <DefaultFooter/>
      </body>
    </html>
  );
}
